apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: barodago-ingress
  namespace: barodago
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/websocket-services: "backend"
spec:
  tls:
  - hosts:
    - api.barodago.com
    - admin.barodago.com
    secretName: barodago-tls
  rules:
  - host: api.barodago.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 8000
  - host: admin.barodago.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: admin
            port:
              number: 80
